apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
  labels:
    app: LoginApplication
spec:
  selector:
    matchLabels:
      app: LoginApplication
      tier: web
  template:
    metadata:
      labels:
        app: LoginApplication
        tier: web
    spec:
      containers:
      - name: login-application
        image: zhaoxuanacr.azurecr.io/task5/loginservice:latest
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: spring-login-config

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-login-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-login-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
