apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
  labels:
    app: ProfileApplication
spec:
  selector:
    matchLabels:
      app: ProfileApplication
      tier: web
  template:
    metadata:
      labels:
        app: ProfileApplication
        tier: web
    spec:
      containers:
      - name: profile-application
        image: us.gcr.io/gcp-docker-kubernetes-960826/profileservice:v001
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: spring-profile-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-profile-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-profile-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
